#include "Engine/UI/Styles/StyleSerialization.h"

#include "Engine/Diagnostics/Diagnostic.h"

namespace px::ui { namespace {
diag::Diagnostic Error(std::string message){return {.severity=diag::Severity::Error,.code="PXSTYLE3250",.category="UI.Style.Serialization",.message=std::move(message)};}
std::optional<Uuid> Id(const Variant& value){if(const auto* id=value.TryGet<Uuid>())return *id;if(const auto* text=value.TryGet<std::string>())return Uuid::Parse(*text);return std::nullopt;}
StyleValue ReadValue(const Variant& value){if(const auto* object=value.AsObject()){if(const auto found=object->find("token");found!=object->end())if(const auto id=Id(found->second))return StyleValue::Token(*id);}return StyleValue::Literal(value.Clone());}
Variant WriteValue(const StyleValue& value){if(value.IsTokenReference())return VariantObject{{"token",value.TokenReference()},{"name",value.LastKnownTokenName()}};if(value.IsLiteral())return value.LiteralValue().Clone();return Variant{};}
void ReadProperties(const VariantObject& source,StylePropertyMap& target){for(const auto& [name,value]:source)target.emplace(name,ReadValue(value));}
VariantObject WriteProperties(const StylePropertyMap& source){VariantObject result;for(const auto& [name,value]:source)if(!value.IsUnset())result.emplace(name,WriteValue(value));return result;}
void ReadBlock(const VariantObject& source,StyleBlock& block){if(const auto found=source.find("properties");found!=source.end())if(const auto* values=found->second.AsObject())ReadProperties(*values,block.properties);if(const auto found=source.find("states");found!=source.end())if(const auto* states=found->second.AsObject())for(const auto& [mask,value]:*states)if(const auto* values=value.AsObject())try{ReadProperties(*values,block.stateOverrides[static_cast<StyleStateMask>(std::stoul(mask))]);}catch(const std::exception&) {}}
VariantObject WriteBlock(const StyleBlock& block){VariantObject states;for(const auto& [mask,values]:block.stateOverrides)states.emplace(std::to_string(mask),WriteProperties(values));return {{"properties",WriteProperties(block.properties)},{"states",std::move(states)}};}
}
Result<ControlStyleBinding> ParseStyleBinding(const Variant& value){const auto* object=value.AsObject();if(!object)return Result<ControlStyleBinding>::Failure(Error("styleBinding must be an Object"));ControlStyleBinding result;
    if(const auto found=object->find("baseStyle");found!=object->end()&&found->second.Type()!=VariantType::Null){const auto id=Id(found->second);if(!id)return Result<ControlStyleBinding>::Failure(Error("baseStyle must be a UUID"));result.baseStyle=*id;}
    if(const auto found=object->find("variants");found!=object->end()){const auto* variants=found->second.AsObject();if(!variants)return Result<ControlStyleBinding>::Failure(Error("variants must be an Object"));for(const auto& [axis,selection]:*variants){const auto axisId=Uuid::Parse(axis),valueId=Id(selection);if(!axisId||!valueId)return Result<ControlStyleBinding>::Failure(Error("variant selection contains an invalid UUID"));result.variants.emplace(*axisId,*valueId);}}
    if(const auto found=object->find("appliedStyles");found!=object->end()){const auto* styles=found->second.AsArray();if(!styles)return Result<ControlStyleBinding>::Failure(Error("appliedStyles must be an Array"));for(const auto& style:*styles){const auto id=Id(style);if(!id)return Result<ControlStyleBinding>::Failure(Error("applied style must be a UUID"));result.appliedStyles.push_back(*id);}}
    if(const auto found=object->find("componentOverrides");found!=object->end()){const auto* values=found->second.AsObject();if(!values)return Result<ControlStyleBinding>::Failure(Error("componentOverrides must be an Object"));ReadProperties(*values,result.componentOverrides);}
    if(const auto found=object->find("localOverrides");found!=object->end()){const auto* values=found->second.AsObject();if(!values)return Result<ControlStyleBinding>::Failure(Error("localOverrides must be an Object"));ReadProperties(*values,result.localOverrides);}return Result<ControlStyleBinding>::Success(std::move(result));}
Variant WriteStyleBinding(const ControlStyleBinding& binding){VariantObject variants;for(const auto& [axis,value]:binding.variants)variants.emplace(axis.ToString(),value);VariantArray applied;for(const auto& style:binding.appliedStyles)applied.emplace_back(style);VariantObject result{{"variants",std::move(variants)},{"appliedStyles",std::move(applied)},{"componentOverrides",WriteProperties(binding.componentOverrides)},{"localOverrides",WriteProperties(binding.localOverrides)}};if(binding.baseStyle)result["baseStyle"]=*binding.baseStyle;return result;}
Result<StyleThemeData> ParseStyleTheme(const Variant& value){const auto* object=value.AsObject();if(!object)return Result<StyleThemeData>::Failure(Error("styleSystem must be an Object"));StyleThemeData theme;const auto versionIt=object->find("version");const auto* version=versionIt==object->end()?nullptr:versionIt->second.TryGet<std::int64_t>();if(!version||*version!=StyleThemeData::CurrentStyleSystemVersion)return Result<StyleThemeData>::Failure(Error("styleSystem version must be 3"));theme.styleSystemVersion=*version;
    if(const auto found=object->find("globalDefaults");found!=object->end())if(const auto* block=found->second.AsObject())ReadBlock(*block,theme.globalDefaults);
    if(const auto found=object->find("controlDefaults");found!=object->end())if(const auto* controls=found->second.AsObject())for(const auto& [type,controlValue]:*controls)if(const auto* block=controlValue.AsObject())ReadBlock(*block,theme.controlTypeDefaults[type]);
    if(const auto found=object->find("tokens");found!=object->end()){const auto* tokens=found->second.AsArray();if(!tokens)return Result<StyleThemeData>::Failure(Error("tokens must be an Array"));for(const auto& item:*tokens){const auto* token=item.AsObject();if(!token)continue;const auto idIt=token->find("id"),nameIt=token->find("name"),valueIt=token->find("value");if(idIt==token->end()||nameIt==token->end()||valueIt==token->end())continue;const auto id=Id(idIt->second);const auto* name=nameIt->second.TryGet<std::string>();if(!id||!name)continue;TokenDefinition definition{.id=*id,.displayName=*name,.type=valueIt->second.Type(),.value=ReadValue(valueIt->second)};(void)theme.UpsertToken(std::move(definition));}}
    if(const auto found=object->find("styles");found!=object->end()){const auto* styles=found->second.AsArray();if(!styles)return Result<StyleThemeData>::Failure(Error("styles must be an Array"));for(const auto& item:*styles){const auto* source=item.AsObject();if(!source)continue;const auto idIt=source->find("id"),nameIt=source->find("name");if(idIt==source->end()||nameIt==source->end())continue;const auto id=Id(idIt->second);const auto* name=nameIt->second.TryGet<std::string>();if(!id||!name)continue;StyleDefinition style;style.id=*id;style.displayName=*name;if(const auto category=source->find("category");category!=source->end())if(const auto* text=category->second.TryGet<std::string>())style.category=*text;ReadBlock(*source,style);(void)theme.UpsertStyle(std::move(style));}}
    if(const auto found=object->find("variantAxes");found!=object->end()){const auto* axes=found->second.AsArray();if(!axes)return Result<StyleThemeData>::Failure(Error("variantAxes must be an Array"));for(const auto& item:*axes){const auto* source=item.AsObject();if(!source)continue;const auto idIt=source->find("id"),nameIt=source->find("name");if(idIt==source->end()||nameIt==source->end())continue;const auto id=Id(idIt->second);const auto* name=nameIt->second.TryGet<std::string>();if(!id||!name)continue;VariantAxisDefinition axis;axis.id=*id;axis.displayName=*name;if(const auto valuesIt=source->find("values");valuesIt!=source->end())if(const auto* values=valuesIt->second.AsArray())for(const auto& valueItem:*values){const auto* valueSource=valueItem.AsObject();if(!valueSource)continue;const auto valueIdIt=valueSource->find("id"),valueNameIt=valueSource->find("name");if(valueIdIt==valueSource->end()||valueNameIt==valueSource->end())continue;const auto valueId=Id(valueIdIt->second);const auto* valueName=valueNameIt->second.TryGet<std::string>();if(!valueId||!valueName)continue;VariantValueDefinition definition;definition.id=*valueId;definition.displayName=*valueName;ReadBlock(*valueSource,definition);axis.values.push_back(std::move(definition));}if(!axis.values.empty())axis.defaultValue=axis.values.front().id;(void)theme.UpsertAxis(std::move(axis));}}
    return Result<StyleThemeData>::Success(std::move(theme));}
Variant WriteStyleTheme(const StyleThemeData& theme){VariantArray tokens;for(const auto& token:theme.tokens)tokens.emplace_back(VariantObject{{"id",token.id},{"name",token.displayName},{"value",WriteValue(token.value)}});VariantArray styles;for(const auto& style:theme.styles){VariantObject value=WriteBlock(style);value["id"]=style.id;value["name"]=style.displayName;value["category"]=style.category;styles.emplace_back(std::move(value));}VariantArray axes;for(const auto& axis:theme.variantAxes){VariantArray values;for(const auto& definition:axis.values){VariantObject value=WriteBlock(definition);value["id"]=definition.id;value["name"]=definition.displayName;values.emplace_back(std::move(value));}axes.emplace_back(VariantObject{{"id",axis.id},{"name",axis.displayName},{"values",std::move(values)}});}VariantObject controls;for(const auto& [type,block]:theme.controlTypeDefaults)controls.emplace(type,WriteBlock(block));return VariantObject{{"version",StyleThemeData::CurrentStyleSystemVersion},{"tokens",std::move(tokens)},{"styles",std::move(styles)},{"variantAxes",std::move(axes)},{"globalDefaults",WriteBlock(theme.globalDefaults)},{"controlDefaults",std::move(controls)}};}
}
