#include "BlueprintEditor.h"

#include <algorithm>
#include <sstream>

namespace ed = ax::NodeEditor;
namespace fs = std::filesystem;

namespace PrismatiX::Editor {

void BlueprintEditor::RenderInspector() {
    if (NodeInstance* selectedNode = FindNode(m_selectedNodeId)) {
        ImGui::TextUnformatted(selectedNode->templateRef->title.c_str());
        ImGui::TextDisabled("%s", selectedNode->templateRef->description.c_str());
        ImGui::Separator();
        for (auto& parameter : selectedNode->parameters) {
            RenderParameterEditor(parameter, "_inspector", false);
        }
        return;
    }

    if (const LinkInstance* link = FindLink(m_selectedLinkId)) {
        ImGui::Text("Link %d", static_cast<int>(link->id.Get()));
        ImGui::TextDisabled("From %d to %d", static_cast<int>(link->startPinId.Get()), static_cast<int>(link->endPinId.Get()));
        return;
    }

    ImGui::TextDisabled("Select a node to edit its parameters, or drop a resource from the explorer onto the active graph.");
}

void BlueprintEditor::NavigateToContent() {
    EnsureEditorContext();
    if (!m_context) {
        return;
    }
    ed::SetCurrentEditor(m_context);
    ed::NavigateToContent();
}

void BlueprintEditor::ApplyAssetToSelection(const std::string& assetPath) {
    NodeInstance* selectedNode = FindNode(m_selectedNodeId);
    if (!selectedNode) {
        Log("Select a node before dropping an asset.");
        return;
    }

    for (auto& parameter : selectedNode->parameters) {
        if (parameter.kind == ParameterKind::Asset || parameter.kind == ParameterKind::String) {
            parameter.stringValue = assetPath;
            MarkSceneDocumentDirty();
            Log("Applied asset to " + selectedNode->templateRef->title + ": " + assetPath);
            return;
        }
    }

    Log("The selected node does not expose a string or asset parameter.");
}

bool BlueprintEditor::HasSelection() const { return static_cast<bool>(m_selectedNodeId) || static_cast<bool>(m_selectedLinkId); }

std::string BlueprintEditor::GetSelectionSummary() const {
    if (const NodeInstance* selectedNode = FindNode(m_selectedNodeId)) {
        return selectedNode->templateRef->title + " node";
    }
    if (FindLink(m_selectedLinkId)) {
        return "Link selection";
    }
    if (m_flavor == BlueprintFlavor::SceneScript) {
        if (const SceneDocument* document = ActiveSceneDocument()) {
            return "Scene Graph: " + document->displayName;
        }
    }
    return "Nothing selected";
}

std::string BlueprintEditor::GenerateLua() const { return m_flavor == BlueprintFlavor::Entrypoint ? EmitEntrypointLua() : EmitScenePds(); }

std::vector<BlueprintEditor::ExportDocument> BlueprintEditor::BuildExportDocuments() const {
    std::vector<ExportDocument> documents;
    if (m_flavor != BlueprintFlavor::SceneScript) {
        return documents;
    }

    documents.reserve(m_sceneDocuments.size());
    const fs::path dataRoot = DataRoot();
    for (size_t index = 0; index < m_sceneDocuments.size(); ++index) {
        const SceneDocument& document = m_sceneDocuments[index];
        ExportDocument exportDocument;
        exportDocument.label = "PDS: " + document.displayName;
        exportDocument.relativePath = dataRoot.empty() ? document.path.filename() : fs::relative(document.path, dataRoot);
        exportDocument.content = index == m_activeSceneDocumentIndex ? EmitScenePds() : document.source;
        documents.push_back(std::move(exportDocument));
    }
    return documents;
}

std::string BlueprintEditor::CurrentDocumentRuntimePath() const {
    if (const SceneDocument* document = ActiveSceneDocument()) {
        return document->runtimePath;
    }
    return {};
}

std::filesystem::path BlueprintEditor::CurrentDocumentPath() const {
    if (const SceneDocument* document = ActiveSceneDocument()) {
        return document->path;
    }
    return {};
}

std::string BlueprintEditor::EmitEntrypointLua() const {
    auto flow = BuildLinearFlow();
    auto findByType = [&](std::string_view typeId) -> const NodeInstance* {
        auto it = std::find_if(flow.begin(), flow.end(), [&](const NodeInstance* node) { return node->templateRef->typeId == typeId; });
        return it == flow.end() ? nullptr : *it;
    };

    const NodeInstance* boot = findByType("boot_runtime");
    const NodeInstance* config = findByType("configure_systems");

    std::vector<const NodeInstance*> bootSteps;
    std::vector<const NodeInstance*> loopSteps;
    bool inLoop = false;
    for (const NodeInstance* node : flow) {
        if (node->templateRef->typeId == "game_loop") {
            inLoop = true;
            continue;
        }
        if (inLoop) {
            loopSteps.push_back(node);
        }
        else {
            bootSteps.push_back(node);
        }
    }

    std::ostringstream lua;
    lua << "-- Generated by PrismatiXEditor\n";
    lua << "local loadedModules = {}\n\n";
    lua << "local function include(path)\n";
    lua << "    if loadedModules[path] then return loadedModules[path] end\n";
    lua << "    local source = Engine.ReadAssetText(path, true)\n";
    lua << "    if not source then error(\"Failed to load script: \" .. path) end\n";
    lua << "    local chunk, err = load(source, \"@\" .. path)\n";
    lua << "    if not chunk then error(\"Lua parse error in \" .. path .. \": \" .. err) end\n";
    lua << "    local result = chunk()\n";
    lua << "    loadedModules[path] = result or true\n";
    lua << "    return result\n";
    lua << "end\n\n";
    lua << "_G.include = include\n";
    lua << "_G.Utils   = include(\"Scripts/common/utils.lua\")\n";
    lua << "_G.Runtime = include(\"Scripts/common/runtime_helpers.lua\")\n";
    lua << "_G.UI      = include(\"Scripts/common/ui_framework.lua\")\n";
    lua << "_G.Ease    = include(\"Scripts/common/easing.lua\")\n\n";
    lua << "local SceneManager        = include(\"Scripts/common/scene_manager.lua\")\n";
    lua << "local Transition          = include(\"Scripts/fx/transition.lua\")\n";
    lua << "local NotificationManager = include(\"Scripts/components/notification.lua\")\n";
    lua << "local FX                  = include(\"Scripts/fx/screen_fx.lua\")\n\n";
    lua << "function Entrypoint()\n";
    lua << "    local gameTitle = " << NormalizeLuaString(boot ? ResolveString(*boot, "game_title") : "PrismatiX Narrative") << "\n";
    lua << "    local fontName = " << NormalizeLuaString(boot ? ResolveString(*boot, "font_name") : "NotoSansTC-Bold.ttf") << "\n";
    lua << "    local fontSize = " << (boot ? ResolveInt(*boot, "font_size") : 32) << "\n";
    lua << "    local transitionStyle = " << NormalizeLuaString(config ? ResolveString(*config, "transition_style") : "dissolve") << "\n";
    lua << "    local transitionSpeed = " << (config ? ResolveInt(*config, "transition_speed") : 10) << "\n";
    lua << "    local notificationSize = " << (config ? ResolveInt(*config, "notification_size") : 20) << "\n\n";
    lua << "    _G.PX = {\n";
    lua << "        Scene        = SceneManager.new(),\n";
    lua << "        Transition   = Transition.new({ style = transitionStyle, speed = transitionSpeed }),\n";
    lua << "        Notification = NotificationManager.new(fontName, notificationSize),\n";
    lua << "        FX           = FX,\n";
    lua << "        GameTitle    = gameTitle,\n";
    lua << "    }\n\n";

    for (const NodeInstance* node : bootSteps) {
        const std::string& typeId = node->templateRef->typeId;
        if (typeId == "run_splashes") {
            lua << "    Runtime.run_splash_script(" << NormalizeLuaString(ResolveString(*node, "engine_splash")) << ")\n";
            lua << "    Runtime.run_splash_script(" << NormalizeLuaString(ResolveString(*node, "game_splash")) << ")\n";
        }
        else if (typeId == "preload_scene") {
            lua << "    include(" << NormalizeLuaString(ResolveString(*node, "scene_module")) << ")\n";
        }
        else if (typeId == "switch_scene") {
            const std::string sceneScript = ResolveString(*node, "scene_script");
            if (!sceneScript.empty()) {
                lua << "    _G.PX.GeneratedSceneScript = " << NormalizeLuaString(sceneScript) << "\n";
            }
            lua << "    local FirstScene = include(" << NormalizeLuaString(ResolveString(*node, "scene_module")) << ")\n";
            lua << "    _G.PX.Scene:switch(FirstScene.new(fontName, fontSize, " << NormalizeLuaString(sceneScript) << "))\n";
        }
    }

    lua << "\n";
    lua << "    while Engine.IsRunning() do\n";
    lua << "        Engine.HandleEvents()\n";
    lua << "        local winW, winH = Engine.GetLogicalSize()\n";
    lua << "        local mx, my = Engine.GetMouseX(), Engine.GetMouseY()\n";
    lua << "        local leftClick = Engine.GetLeftClick()\n";
    lua << "        local rightClick = Engine.GetRightClick()\n\n";

    for (const NodeInstance* node : loopSteps) {
        const std::string& typeId = node->templateRef->typeId;
        if (typeId == "update_fx") {
            lua << "        _G.PX.FX.update()\n";
            lua << "        local ox, oy = _G.PX.FX.get_offset()\n";
            lua << "        Engine.SetCameraOffset(ox, oy)\n";
        }
        else if (typeId == "update_notification") {
            lua << "        _G.PX.Notification:update()\n";
        }
        else if (typeId == "update_transition") {
            lua << "        _G.PX.Transition:update(winW)\n";
        }
        else if (typeId == "update_scene") {
            lua << "        _G.PX.Scene:update(mx, my, leftClick, rightClick)\n";
        }
        else if (typeId == "clear_screen") {
            lua << "        Engine.ClearScreen(" << ResolveInt(*node, "red") << ", " << ResolveInt(*node, "green") << ", " << ResolveInt(*node, "blue") << ", " << ResolveInt(*node, "alpha") << ")\n";
        }
        else if (typeId == "render_scene") {
            lua << "        _G.PX.Scene:render(winW, winH)\n";
        }
        else if (typeId == "render_notification") {
            lua << "        _G.PX.Notification:render(winW, winH)\n";
        }
        else if (typeId == "render_transition") {
            lua << "        _G.PX.Transition:draw_fullscreen(winW, winH)\n";
        }
        else if (typeId == "present_frame") {
            lua << "        Engine.PresentScreen()\n";
        }
    }

    lua << "    end\n";
    lua << "end\n";
    return lua.str();
}

std::string BlueprintEditor::EmitScenePds() const {
    auto flow = BuildLinearFlow();
    auto findByType = [&](std::string_view typeId) -> const NodeInstance* {
        auto it = std::find_if(flow.begin(), flow.end(), [&](const NodeInstance* node) { return node->templateRef->typeId == typeId; });
        return it == flow.end() ? nullptr : *it;
    };

    const NodeInstance* entry = findByType("scene_entry");
    const std::string sceneName = entry ? ResolveString(*entry, "scene_name") : "chapter1";
    const std::string heading = entry ? ResolveString(*entry, "heading") : "";

    std::ostringstream script;
    if (!heading.empty()) {
        script << "# " << heading << "\n\n";
    } else if (!sceneName.empty()) {
        script << "# " << sceneName << "\n\n";
    }

    for (const NodeInstance* node : flow) {
        const std::string& typeId = node->templateRef->typeId;
        if (typeId == "scene_entry") {
            continue;
        }
        if (typeId == "set_background") {
            script << "[bg file=" << NormalizeLuaString(ResolveString(*node, "background")) << "]\n";
        }
        else if (typeId == "play_bgm") {
            const std::string bgm = ResolveString(*node, "bgm");
            script << "[bgm file=" << NormalizeLuaString(bgm) << "]\n";
        }
        else if (typeId == "show_dialogue") {
            const std::string speaker = ResolveString(*node, "speaker");
            script << "[text";
            if (!speaker.empty()) {
                script << " speaker=" << NormalizeLuaString(speaker);
            }
            script << "]\n";
            script << ResolveString(*node, "text") << "\n";
        }
        else if (typeId == "transition") {
            script << "[lua fn=" << NormalizeLuaString("PXEditorTransition") << " style=" << NormalizeLuaString(ResolveString(*node, "style")) << " speed=" << NormalizeLuaString(std::to_string(ResolveFloat(*node, "speed"))) << "]\n";
        }
        else if (typeId == "animate_actor") {
            script << "[lua fn=" << NormalizeLuaString("PXEditorAnimateActor") << " target=" << NormalizeLuaString(ResolveString(*node, "target")) << " duration=" << NormalizeLuaString(std::to_string(ResolveFloat(*node, "duration")))
                   << " move_x=" << NormalizeLuaString(std::to_string(ResolveFloat(*node, "move_x"))) << "]\n";
        }
        else if (typeId == "spawn_ui") {
            script << "[lua fn=" << NormalizeLuaString("PXEditorSpawnUI") << " ui_script=" << NormalizeLuaString(ResolveString(*node, "ui_script")) << "]\n";
        }
        else if (typeId == "present_choice") {
            for (const char suffix : { 'a', 'b', 'c', 'd' }) {
                const std::string option = ResolveString(*node, std::string("option_") + suffix);
                const std::string target = ResolveString(*node, std::string("option_") + suffix + "_target");
                if (!option.empty()) {
                    script << "[choice text=" << NormalizeLuaString(option) << " target=" << NormalizeLuaString(target) << "]\n";
                }
            }
        }
        else if (typeId == "wait_input") {
            script << "[wait auto_advance=" << NormalizeLuaString(ResolveBool(*node, "auto_advance") ? "true" : "false") << "]\n";
        }
        else if (typeId == "jump_scene") {
            script << "[jump target=" << NormalizeLuaString(ResolveString(*node, "target_scene")) << "]\n";
        }
        else if (typeId == "scene_label") {
            script << "*" << ResolveString(*node, "label") << "\n";
        }
        else if (typeId == "character_state") {
            script << "[char id=" << NormalizeLuaString(ResolveString(*node, "char_id")) << " expression=" << NormalizeLuaString(ResolveString(*node, "expression")) << " pos=" << NormalizeLuaString(ResolveString(*node, "position")) << "]\n";
        }
        else if (typeId == "set_variable") {
            script << "[var var=" << NormalizeLuaString(ResolveString(*node, "var_name")) << " op=" << NormalizeLuaString(ResolveString(*node, "op")) << " val=" << NormalizeLuaString(ResolveString(*node, "value")) << "]\n";
        }
        else if (typeId == "run_lua") {
            script << "[lua fn=" << NormalizeLuaString(ResolveString(*node, "fn"));
            const std::string args = ResolveString(*node, "args");
            if (!args.empty()) {
                script << " " << args;
            }
            script << "]\n";
        }
        else if (typeId == "stop_bgm") {
            script << "[stopbgm]\n";
        }
        else if (typeId == "raw_command") {
            script << ResolveString(*node, "command") << "\n";
        }

        script << "\n";
    }

    return script.str();
}

std::vector<std::string> BlueprintEditor::BuildPreviewLines() const {
    std::vector<std::string> lines;
    auto flow = BuildLinearFlow();

    if (m_flavor == BlueprintFlavor::Entrypoint) {
        auto findByType = [&](std::string_view typeId) -> const NodeInstance* {
            auto it = std::find_if(flow.begin(), flow.end(), [&](const NodeInstance* node) { return node->templateRef->typeId == typeId; });
            return it == flow.end() ? nullptr : *it;
        };

        if (const NodeInstance* boot = findByType("boot_runtime")) {
            lines.push_back("Font: " + ResolveString(*boot, "font_name") + " / " + std::to_string(ResolveInt(*boot, "font_size")) + "px");
        }
        if (const NodeInstance* config = findByType("configure_systems")) {
            lines.push_back("Transition: " + ResolveString(*config, "transition_style") + " @ " + std::to_string(ResolveInt(*config, "transition_speed")));
        }
        if (const NodeInstance* splash = findByType("run_splashes")) {
            lines.push_back("Splash: " + ResolveString(*splash, "engine_splash"));
            lines.push_back("Splash: " + ResolveString(*splash, "game_splash"));
        }
        if (const NodeInstance* startScene = findByType("switch_scene")) {
            lines.push_back("Start Scene: " + ResolveString(*startScene, "scene_module"));
            const std::string sceneScript = ResolveString(*startScene, "scene_script");
            if (!sceneScript.empty()) {
                lines.push_back("Scene Script: " + sceneScript);
            }
        }

        std::ostringstream loopSequence;
        loopSequence << "Loop: ";
        bool started = false;
        bool inLoop = false;
        for (const NodeInstance* node : flow) {
            if (node->templateRef->typeId == "game_loop") {
                inLoop = true;
                continue;
            }
            if (!inLoop) {
                continue;
            }
            if (started) {
                loopSequence << " -> ";
            }
            loopSequence << node->templateRef->title;
            started = true;
        }
        if (started) {
            lines.push_back(loopSequence.str());
        }
    }
    else {
        auto findByType = [&](std::string_view typeId) -> const NodeInstance* {
            auto it = std::find_if(flow.begin(), flow.end(), [&](const NodeInstance* node) { return node->templateRef->typeId == typeId; });
            return it == flow.end() ? nullptr : *it;
        };

        if (const NodeInstance* entry = findByType("scene_entry")) {
            lines.push_back("Scene: " + ResolveString(*entry, "scene_name"));
            const std::string runtimePath = CurrentDocumentRuntimePath();
            if (!runtimePath.empty()) {
                lines.push_back("PDS: " + runtimePath);
            }
        }
        if (const NodeInstance* bgm = findByType("play_bgm")) {
            lines.push_back("BGM: " + ResolveString(*bgm, "bgm"));
        }
        if (const NodeInstance* dialogue = findByType("show_dialogue")) {
            lines.push_back("Speaker: " + ResolveString(*dialogue, "speaker"));
            lines.push_back("Line: " + ResolveString(*dialogue, "text"));
        }
        if (const NodeInstance* transition = findByType("transition")) {
            lines.push_back("Transition: " + ResolveString(*transition, "style"));
        }
        if (const NodeInstance* choice = findByType("present_choice")) {
            lines.push_back("Choice: " + ResolveString(*choice, "option_a") + " / " + ResolveString(*choice, "option_b"));
        }
    }

    return lines;
}

std::string BlueprintEditor::NormalizeLuaString(const std::string& value) const {
    std::string sanitized;
    sanitized.reserve(value.size() + 8);
    for (char ch : value) {
        switch (ch) {
            case '\\':
                sanitized += "\\\\";
                break;
            case '"':
                sanitized += "\\\"";
                break;
            case '\n':
                sanitized += "\\n";
                break;
            case '\r':
                break;
            default:
                sanitized += ch;
                break;
        }
    }

    return "\"" + sanitized + "\"";
}

void BlueprintEditor::Log(const std::string& message) const {
    if (m_logCallback) {
        m_logCallback(message);
    }
}

}  // namespace PrismatiX::Editor
