#include "Engine/Text/Typography.h"
#include <algorithm>

namespace px::text { namespace {
std::vector<std::string> Glyphs(std::string_view value){std::vector<std::string> result;for(std::size_t index=0;index<value.size();){const unsigned char lead=value[index];std::size_t count=lead<0x80?1:(lead&0xE0)==0xC0?2:(lead&0xF0)==0xE0?3:4;count=std::min(count,value.size()-index);result.emplace_back(value.substr(index,count));index+=count;}return result;}
bool In(std::string_view glyph,std::string_view set){return set.find(glyph)!=std::string_view::npos;}
}
RichText ParseRubyMarkup(std::string_view markup){RichText result;for(std::size_t index=0;index<markup.size();){if(markup.substr(index).starts_with("[br]")){result.plain+='\n';index+=4;continue;}if(markup.substr(index).starts_with("[ruby=")){const auto header=markup.find(']',index),close=markup.find("[/ruby]",header==std::string_view::npos?index:header);if(header!=std::string_view::npos&&close!=std::string_view::npos){const std::string reading(markup.substr(index+6,header-index-6)),base(markup.substr(header+1,close-header-1));result.ruby.push_back({result.plain,base,reading});result.plain+=base;index=close+7;continue;}}if(markup[index]=='['){const auto close=markup.find(']',index);if(close!=std::string_view::npos){index=close+1;continue;}}result.plain.push_back(markup[index++]);}return result;}
std::string ApplyCjkKinsoku(std::string_view text,std::size_t maxColumns){if(maxColumns==0)return std::string(text);const auto glyphs=Glyphs(text);std::string output;std::size_t column=0;constexpr std::string_view noStart="、。，．！？)]｝」』】》〉”’ー";constexpr std::string_view noEnd="([｛「『【《〈“‘";for(std::size_t i=0;i<glyphs.size();++i){const auto& glyph=glyphs[i];if(glyph=="\n"){output+=glyph;column=0;continue;}if(column>=maxColumns&&!In(glyph,noStart)){if(!output.empty()&&i>0&&In(glyphs[i-1],noEnd)){}else{output+='\n';column=0;}}output+=glyph;++column;}return output;}
std::vector<VerticalGlyph> LayoutVertical(std::string_view text,std::size_t rowsPerColumn){rowsPerColumn=std::max<std::size_t>(1,rowsPerColumn);std::vector<VerticalGlyph> result;int column=0,row=0;for(const auto& glyph:Glyphs(text)){if(glyph=="\n"||row>=static_cast<int>(rowsPerColumn)){++column;row=0;if(glyph=="\n")continue;}const bool rotate=glyph.size()==1&&glyph[0]>=0x21&&glyph[0]<=0x7e;result.push_back({glyph,column,row++,rotate});}return result;}
}  // namespace px::text
