if(NOT DEFINED PREVIEW_HOST OR NOT EXISTS "${PREVIEW_HOST}")
    message(FATAL_ERROR "PreviewHost executable is missing")
endif()
if(NOT DEFINED FIXTURE_ROOT OR NOT EXISTS "${FIXTURE_ROOT}/debug.pxir")
    message(FATAL_ERROR "PreviewHost Lua debugger fixture is missing")
endif()
if(NOT DEFINED INPUT_FILE)
    message(FATAL_ERROR "PreviewHost Lua debugger input path is missing")
endif()

file(TO_CMAKE_PATH "${FIXTURE_ROOT}" PROJECT_ROOT)
set(ENVELOPE "\"protocol\":\"PrismatiXPreviewProtocol\",\"schemaRevision\":1,\"protocolVersion\":1,\"sessionId\":\"lua-debug-session\"")
set(INPUT "{\"type\":\"hello\",${ENVELOPE},\"requestId\":\"hello-debug\",\"documentId\":\"\",\"revision\":0}\n")
string(APPEND INPUT "{\"type\":\"applyRuntimeIr\",${ENVELOPE},\"requestId\":\"apply-debug\",\"documentId\":\"lua-debug-document\",\"revision\":1,\"projectRoot\":\"${PROJECT_ROOT}\",\"committedRevision\":1,\"irPath\":\"debug.pxir\"}\n")
string(APPEND INPUT "{\"type\":\"setLuaBreakpoints\",${ENVELOPE},\"requestId\":\"breakpoints-debug\",\"documentId\":\"lua-debug-document\",\"revision\":1,\"breakpoints\":[{\"source\":\"Content/Extensions/debug.lua\",\"line\":3}]}\n")
string(APPEND INPUT "{\"type\":\"advance\",${ENVELOPE},\"requestId\":\"advance-show-all\",\"documentId\":\"lua-debug-document\",\"revision\":1}\n")
string(APPEND INPUT "{\"type\":\"advance\",${ENVELOPE},\"requestId\":\"advance-debug\",\"documentId\":\"lua-debug-document\",\"revision\":1}\n")
string(APPEND INPUT "{\"type\":\"evaluateLuaWatches\",${ENVELOPE},\"requestId\":\"watch-breakpoint\",\"documentId\":\"lua-debug-document\",\"revision\":1,\"watches\":[\"amount\"]}\n")
string(APPEND INPUT "{\"type\":\"luaStep\",${ENVELOPE},\"requestId\":\"lua-step\",\"documentId\":\"lua-debug-document\",\"revision\":1}\n")
string(APPEND INPUT "{\"type\":\"evaluateLuaWatches\",${ENVELOPE},\"requestId\":\"watch-step\",\"documentId\":\"lua-debug-document\",\"revision\":1,\"watches\":[\"amount\"]}\n")
string(APPEND INPUT "{\"type\":\"luaContinue\",${ENVELOPE},\"requestId\":\"lua-continue\",\"documentId\":\"lua-debug-document\",\"revision\":1}\n")
string(APPEND INPUT "{\"type\":\"shutdown\",${ENVELOPE},\"requestId\":\"shutdown-debug\",\"documentId\":\"\",\"revision\":0}\n")
file(WRITE "${INPUT_FILE}" "${INPUT}")

execute_process(
    COMMAND "${PREVIEW_HOST}"
    INPUT_FILE "${INPUT_FILE}"
    OUTPUT_VARIABLE OUTPUT
    ERROR_VARIABLE ERRORS
    RESULT_VARIABLE RESULT
    TIMEOUT 20
)
if(NOT RESULT EQUAL 0)
    message(FATAL_ERROR "PreviewHost Lua debugger fixture failed (${RESULT}): ${ERRORS}")
endif()

string(REPLACE "\r\n" "\n" OUTPUT "${OUTPUT}")
string(REGEX REPLACE "\n+$" "" OUTPUT "${OUTPUT}")
string(REPLACE "\n" ";" OUTPUT_LINES "${OUTPUT}")

set(APPLY_ACK FALSE)
set(BREAKPOINTS_ACK FALSE)
set(SHOW_ALL_ACK FALSE)
set(ADVANCE_ACK FALSE)
set(BREAKPOINT_WATCH_ACK FALSE)
set(STEP_ACK FALSE)
set(STEP_WATCH_ACK FALSE)
set(CONTINUE_ACK FALSE)
set(SHUTDOWN_ACK FALSE)
set(BREAKPOINT_EVENT FALSE)
set(STEP_EVENT FALSE)
set(PRINT_EVENT FALSE)
set(WARN_EVENT FALSE)

foreach(LINE IN LISTS OUTPUT_LINES)
    string(JSON TYPE GET "${LINE}" type)
    string(JSON REQUEST_ID GET "${LINE}" requestId)

    if(TYPE STREQUAL "runtimeIrApplied")
        if(NOT REQUEST_ID STREQUAL "apply-debug")
            message(FATAL_ERROR "Runtime IR apply acknowledgement lost correlation: ${LINE}")
        endif()
        string(JSON CHARACTER_COUNT GET "${LINE}" characterCount)
        string(JSON CHARACTER_REVISION GET "${LINE}" characterResourcesRevision)
        string(JSON CATALOG_REVISION GET "${LINE}" gameCatalogResourcesRevision)
        string(JSON VARIABLE_COUNT GET "${LINE}" gameCatalogVariableCount)
        string(JSON BINDING_COUNT GET "${LINE}" gameCatalogInputBindingCount)
        string(JSON GALLERY_COUNT GET "${LINE}" gameCatalogGalleryItemCount)
        if(NOT CHARACTER_COUNT EQUAL 1 OR NOT CHARACTER_REVISION EQUAL 1)
            message(FATAL_ERROR "PreviewHost did not load characterResources revision 1: ${LINE}")
        endif()
        if(NOT CATALOG_REVISION EQUAL 1 OR NOT VARIABLE_COUNT EQUAL 1 OR
           NOT BINDING_COUNT EQUAL 1 OR NOT GALLERY_COUNT EQUAL 1)
            message(FATAL_ERROR "PreviewHost did not load GameCatalog resources revision 1: ${LINE}")
        endif()
        set(APPLY_ACK TRUE)
    elseif(TYPE STREQUAL "luaBreakpointsSet")
        string(JSON BREAKPOINT_COUNT LENGTH "${LINE}" luaBreakpoints)
        if(NOT REQUEST_ID STREQUAL "breakpoints-debug" OR
           NOT BREAKPOINT_COUNT EQUAL 1)
            message(FATAL_ERROR "Lua breakpoint was not verified: ${LINE}")
        endif()
        set(BREAKPOINTS_ACK TRUE)
    elseif(TYPE STREQUAL "advanceAccepted")
        if(REQUEST_ID STREQUAL "advance-show-all")
            set(SHOW_ALL_ACK TRUE)
        elseif(REQUEST_ID STREQUAL "advance-debug")
            set(ADVANCE_ACK TRUE)
        else()
            message(FATAL_ERROR "Advance acknowledgement lost correlation: ${LINE}")
        endif()
    elseif(TYPE STREQUAL "luaWatchesEvaluated")
        string(JSON AVAILABLE GET "${LINE}" luaWatches 0 available)
        string(JSON VALUE GET "${LINE}" luaWatches 0 value)
        if(REQUEST_ID STREQUAL "watch-breakpoint")
            if(NOT AVAILABLE OR NOT VALUE MATCHES "^2")
                message(FATAL_ERROR "Breakpoint watch did not expose amount: ${LINE}")
            endif()
            set(BREAKPOINT_WATCH_ACK TRUE)
        elseif(REQUEST_ID STREQUAL "watch-step")
            if(NOT AVAILABLE OR NOT VALUE MATCHES "^2")
                message(FATAL_ERROR "Step watch did not expose amount: ${LINE}")
            endif()
            set(STEP_WATCH_ACK TRUE)
        endif()
    elseif(TYPE STREQUAL "luaStepAccepted")
        if(NOT REQUEST_ID STREQUAL "lua-step")
            message(FATAL_ERROR "Lua step acknowledgement lost correlation: ${LINE}")
        endif()
        set(STEP_ACK TRUE)
    elseif(TYPE STREQUAL "luaContinueAccepted")
        if(NOT REQUEST_ID STREQUAL "lua-continue")
            message(FATAL_ERROR "Lua continue acknowledgement lost correlation: ${LINE}")
        endif()
        set(CONTINUE_ACK TRUE)
    elseif(TYPE STREQUAL "shutdownAccepted")
        set(SHUTDOWN_ACK TRUE)
    elseif(TYPE STREQUAL "debug")
        string(JSON ASYNC GET "${LINE}" async)
        if(NOT ASYNC)
            continue()
        endif()
        string(JSON LUA_PAUSED_TYPE ERROR_VARIABLE LUA_PAUSED_ERROR TYPE
               "${LINE}" luaPaused)
        if(LUA_PAUSED_ERROR OR NOT LUA_PAUSED_TYPE STREQUAL "BOOLEAN")
            continue()
        endif()
        string(JSON LUA_PAUSED GET "${LINE}" luaPaused)
        if(NOT LUA_PAUSED)
            continue()
        endif()
        string(JSON REASON GET "${LINE}" luaPauseReason)
        string(JSON STACK_COUNT LENGTH "${LINE}" luaCallStack)
        string(JSON SOURCE GET "${LINE}" luaCallStack 0 source)
        string(JSON SOURCE_LINE GET "${LINE}" luaCallStack 0 line)
        string(JSON LOCALS_COUNT LENGTH "${LINE}" luaCallStack 0 locals)
        if(REQUEST_ID STREQUAL "advance-debug")
            if(NOT ADVANCE_ACK OR NOT REASON STREQUAL "breakpoint" OR
               NOT SOURCE STREQUAL "Content/Extensions/debug.lua" OR
               NOT SOURCE_LINE EQUAL 3 OR STACK_COUNT LESS 1 OR
               LOCALS_COUNT LESS 2)
                message(FATAL_ERROR "Async Lua breakpoint payload is incomplete or preceded its acknowledgement: ${LINE}")
            endif()
            set(BREAKPOINT_EVENT TRUE)
        elseif(REQUEST_ID STREQUAL "lua-step")
            if(NOT STEP_ACK OR NOT REASON STREQUAL "step" OR
               NOT SOURCE STREQUAL "Content/Extensions/debug.lua" OR
               NOT SOURCE_LINE EQUAL 4 OR STACK_COUNT LESS 1 OR
               LOCALS_COUNT LESS 2)
                message(FATAL_ERROR "Async Lua step payload is incomplete or preceded its acknowledgement: ${LINE}")
            endif()
            set(STEP_EVENT TRUE)
        endif()
    elseif(TYPE STREQUAL "output")
        string(JSON SCOPE ERROR_VARIABLE SCOPE_ERROR GET "${LINE}" scope)
        if(SCOPE_ERROR OR NOT SCOPE STREQUAL "lua")
            continue()
        endif()
        string(JSON MESSAGE GET "${LINE}" message)
        string(JSON LEVEL GET "${LINE}" level)
        string(JSON SOURCE GET "${LINE}" source)
        string(JSON SOURCE_LINE GET "${LINE}" line)
        if(MESSAGE MATCHES "^lua-print")
            if(NOT REQUEST_ID STREQUAL "lua-step" OR NOT STEP_ACK OR
               NOT LEVEL STREQUAL "info" OR
               NOT SOURCE STREQUAL "Content/Extensions/debug.lua" OR
               NOT SOURCE_LINE EQUAL 3)
                message(FATAL_ERROR "Lua print event lost source, correlation, or ack ordering: ${LINE}")
            endif()
            set(PRINT_EVENT TRUE)
        elseif(MESSAGE MATCHES "^lua-warn")
            if(NOT REQUEST_ID STREQUAL "lua-continue" OR NOT CONTINUE_ACK OR
               NOT LEVEL STREQUAL "warning" OR
               NOT SOURCE STREQUAL "Content/Extensions/debug.lua" OR
               NOT SOURCE_LINE EQUAL 5)
                message(FATAL_ERROR "Lua warn event lost source, correlation, or ack ordering: ${LINE}")
            endif()
            set(WARN_EVENT TRUE)
        endif()
    endif()
endforeach()

if(NOT APPLY_ACK OR NOT BREAKPOINTS_ACK OR NOT SHOW_ALL_ACK OR NOT ADVANCE_ACK OR
   NOT BREAKPOINT_WATCH_ACK OR NOT STEP_ACK OR NOT STEP_WATCH_ACK OR
   NOT CONTINUE_ACK OR NOT SHUTDOWN_ACK)
    message(FATAL_ERROR "PreviewHost Lua debugger acknowledgements are incomplete: ${OUTPUT}")
endif()
if(NOT BREAKPOINT_EVENT OR NOT STEP_EVENT OR NOT PRINT_EVENT OR NOT WARN_EVENT)
    message(FATAL_ERROR "PreviewHost Lua async debugger/console events are incomplete: ${OUTPUT}")
endif()
