if(NOT DEFINED PREVIEW_HOST OR NOT EXISTS "${PREVIEW_HOST}")
    message(FATAL_ERROR "PreviewHost executable is missing")
endif()
if(NOT DEFINED FIXTURE_ROOT OR NOT EXISTS "${FIXTURE_ROOT}/typed-action.pxir")
    message(FATAL_ERROR "PreviewHost typed Action fixture is missing")
endif()
if(NOT DEFINED INPUT_FILE)
    message(FATAL_ERROR "PreviewHost typed Action input path is missing")
endif()

file(TO_CMAKE_PATH "${FIXTURE_ROOT}" PROJECT_ROOT)
set(ENVELOPE "\"protocol\":\"PrismatiXPreviewProtocol\",\"schemaRevision\":2,\"protocolVersion\":2,\"sessionId\":\"script-action-session\"")
set(INPUT "{\"type\":\"hello\",${ENVELOPE},\"requestId\":\"hello-action\",\"documentId\":\"\",\"revision\":0}\n")
string(APPEND INPUT "{\"type\":\"applyRuntimeIr\",${ENVELOPE},\"requestId\":\"apply-action\",\"documentId\":\"typed-action-document\",\"revision\":1,\"projectRoot\":\"${PROJECT_ROOT}\",\"committedRevision\":1,\"irPath\":\"typed-action.pxir\"}\n")
string(APPEND INPUT "{\"type\":\"advance\",${ENVELOPE},\"requestId\":\"reveal-intro\",\"documentId\":\"typed-action-document\",\"revision\":1}\n")
string(APPEND INPUT "{\"type\":\"advance\",${ENVELOPE},\"requestId\":\"advance-valid-action\",\"documentId\":\"typed-action-document\",\"revision\":1}\n")
string(APPEND INPUT "{\"type\":\"capture\",${ENVELOPE},\"requestId\":\"capture-valid-action\",\"documentId\":\"typed-action-document\",\"revision\":1}\n")
string(APPEND INPUT "{\"type\":\"advance\",${ENVELOPE},\"requestId\":\"reveal-between\",\"documentId\":\"typed-action-document\",\"revision\":1}\n")
string(APPEND INPUT "{\"type\":\"advance\",${ENVELOPE},\"requestId\":\"advance-invalid-action\",\"documentId\":\"typed-action-document\",\"revision\":1}\n")
string(APPEND INPUT "{\"type\":\"capture\",${ENVELOPE},\"requestId\":\"capture-invalid-action\",\"documentId\":\"typed-action-document\",\"revision\":1}\n")
string(APPEND INPUT "{\"type\":\"shutdown\",${ENVELOPE},\"requestId\":\"shutdown-action\",\"documentId\":\"\",\"revision\":0}\n")
file(WRITE "${INPUT_FILE}" "${INPUT}")

execute_process(
    COMMAND "${PREVIEW_HOST}"
    INPUT_FILE "${INPUT_FILE}"
    OUTPUT_VARIABLE OUTPUT
    ERROR_VARIABLE ERRORS
    RESULT_VARIABLE RESULT
    TIMEOUT 20
)
if(NOT RESULT EQUAL 0)
    message(FATAL_ERROR "PreviewHost typed Action fixture failed (${RESULT}): ${ERRORS}")
endif()

string(REPLACE "\r\n" "\n" OUTPUT "${OUTPUT}")
string(REGEX REPLACE "\n+$" "" OUTPUT "${OUTPUT}")
string(REPLACE "\n" ";" OUTPUT_LINES "${OUTPUT}")

set(APPLY_ACK FALSE)
set(VALID_ADVANCE_ACK FALSE)
set(INVALID_ADVANCE_ACK FALSE)
set(VALID_CAPTURE FALSE)
set(INVALID_CAPTURE FALSE)
set(PENDING_STATE FALSE)
set(RESUMED_STATE FALSE)
set(ACTION_START_OUTPUT FALSE)
set(ACTION_COMPLETE_OUTPUT FALSE)
set(INVALID_DIAGNOSTIC FALSE)
set(SHUTDOWN_ACK FALSE)

foreach(LINE IN LISTS OUTPUT_LINES)
    string(JSON TYPE GET "${LINE}" type)
    string(JSON REQUEST_ID GET "${LINE}" requestId)

    if(TYPE STREQUAL "runtimeIrApplied")
        if(NOT REQUEST_ID STREQUAL "apply-action")
            message(FATAL_ERROR "Runtime IR apply acknowledgement lost correlation: ${LINE}")
        endif()
        set(APPLY_ACK TRUE)
    elseif(TYPE STREQUAL "advanceAccepted")
        if(REQUEST_ID STREQUAL "advance-valid-action")
            set(VALID_ADVANCE_ACK TRUE)
        elseif(REQUEST_ID STREQUAL "advance-invalid-action")
            set(INVALID_ADVANCE_ACK TRUE)
        endif()
    elseif(TYPE STREQUAL "state")
        string(JSON SCOPE GET "${LINE}" scope)
        if(NOT SCOPE STREQUAL "runtime" OR
           NOT REQUEST_ID STREQUAL "advance-valid-action")
            continue()
        endif()
        string(JSON STATE GET "${LINE}" state)
        if(STATE STREQUAL "waitingExternal")
            if(NOT VALID_ADVANCE_ACK)
                message(FATAL_ERROR "Action pending state preceded its acknowledgement: ${LINE}")
            endif()
            set(PENDING_STATE TRUE)
        elseif(STATE STREQUAL "waitingClick")
            set(RESUMED_STATE TRUE)
        endif()
    elseif(TYPE STREQUAL "output")
        string(JSON SCOPE ERROR_VARIABLE SCOPE_ERROR GET "${LINE}" scope)
        if(SCOPE_ERROR OR NOT SCOPE STREQUAL "script" OR
           NOT REQUEST_ID STREQUAL "advance-valid-action")
            continue()
        endif()
        string(JSON MESSAGE GET "${LINE}" message)
        string(JSON SOURCE GET "${LINE}" source)
        if(NOT SOURCE STREQUAL "Content/Extensions/debug.js")
            message(FATAL_ERROR "Typed Action output lost its script source: ${LINE}")
        endif()
        if(MESSAGE MATCHES "^typed-action-start")
            set(ACTION_START_OUTPUT TRUE)
        elseif(MESSAGE MATCHES "^typed-action-complete")
            set(ACTION_COMPLETE_OUTPUT TRUE)
        endif()
        if(MESSAGE MATCHES "99")
            message(FATAL_ERROR "Invalid typed Action reached the script callback: ${LINE}")
        endif()
    elseif(TYPE STREQUAL "stateCaptured")
        string(JSON ACTION_RESULT GET "${LINE}" variables typed_action_result)
        if(NOT ACTION_RESULT EQUAL 6)
            message(FATAL_ERROR "Typed Action result was not preserved: ${LINE}")
        endif()
        if(REQUEST_ID STREQUAL "capture-valid-action")
            set(VALID_CAPTURE TRUE)
        elseif(REQUEST_ID STREQUAL "capture-invalid-action")
            set(INVALID_CAPTURE TRUE)
        endif()
    elseif(TYPE STREQUAL "diagnostics" AND
           REQUEST_ID STREQUAL "advance-invalid-action")
        string(JSON DIAGNOSTIC_COUNT LENGTH "${LINE}" diagnostics)
        math(EXPR LAST_DIAGNOSTIC "${DIAGNOSTIC_COUNT} - 1")
        foreach(INDEX RANGE 0 ${LAST_DIAGNOSTIC})
            string(JSON CODE GET "${LINE}" diagnostics ${INDEX} code)
            if(CODE STREQUAL "PXUIACTION2015")
                set(INVALID_DIAGNOSTIC TRUE)
            endif()
        endforeach()
    elseif(TYPE STREQUAL "shutdownAccepted")
        set(SHUTDOWN_ACK TRUE)
    endif()
endforeach()

if(NOT APPLY_ACK OR NOT VALID_ADVANCE_ACK OR NOT INVALID_ADVANCE_ACK OR
   NOT VALID_CAPTURE OR NOT INVALID_CAPTURE OR NOT PENDING_STATE OR
   NOT RESUMED_STATE OR NOT ACTION_START_OUTPUT OR NOT ACTION_COMPLETE_OUTPUT OR
   NOT INVALID_DIAGNOSTIC OR NOT SHUTDOWN_ACK)
    message(FATAL_ERROR "PreviewHost typed Action process evidence is incomplete: ${OUTPUT}")
endif()
