# Authoritative revisions for public PrismatiX wire contracts.
#
# Templates and the generated C++ header consume these values. Do not duplicate
# public revision numbers in manifests or source headers.
set(PRISMATIX_CHARACTER_RESOURCES_CONTRACT_REVISION 1)
set(PRISMATIX_GAME_CATALOG_RESOURCES_CONTRACT_REVISION 1)
set(PRISMATIX_PACKAGER_CONTRACT_REVISION 1)
set(PRISMATIX_RUNTIME_IR_CONTRACT_REVISION 1)
set(PRISMATIX_UI_CONTRACT_REVISION 2)
set(PRISMATIX_STUDIO_UI_COMPAT_CONTRACT_REVISION 1)
set(PRISMATIX_UI_TYPE_REGISTRY_SCHEMA_REVISION 2)
set(PRISMATIX_UI_TYPE_REGISTRY_CONTRACT_REVISION 2)
set(PRISMATIX_PREVIEW_SCHEMA_REVISION 2)
set(PRISMATIX_PREVIEW_PROTOCOL_VERSION 2)
set(PRISMATIX_AUTHORING_CONTRACT_REVISION 1)
